name: test

on:
  push: {}
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: 3dmr
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.6.15'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/3dmr
      run: |
        python manage.py makemigrations
        python manage.py migrate

    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/3dmr
      run: |
        python manage.py test